// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-services.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var list_services_default = defineTool({
  name: "list_services",
  title: "List Setupr services",
  description: "List Setupr's public services catalog (business registration, websites & integrations, automations & AI). Returns service id, name, category, short description, who it's for, Setupr fee (INR), delivery type, and regional availability.",
  inputSchema: {
    category: z.string().optional().describe(
      "Optional category filter: 'business-registration', 'websites-integrations', 'automations-ai', etc."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("services").select(
      "service_id, service_name, category, sub_category, description_short, who_its_for, setupr_fee_inr, govt_or_third_party_fee, delivery_type, available_regions, is_regional"
    ).eq("visibility", "public").order("sort_order");
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_blog_posts_default = defineTool2({
  name: "list_blog_posts",
  title: "List Setupr blog posts",
  description: "List published Setupr blog posts (title, slug, excerpt, category, author, published date, read time, featured image). Returns most recently published first.",
  inputSchema: {
    category: z2.string().optional().describe("Optional category filter."),
    limit: z2.number().int().optional().describe("Max number of posts to return. Defaults to 20, capped at 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const cap = Math.min(Math.max(limit ?? 20, 1), 50);
    let query = supabase.from("blog_posts").select(
      "title, slug, excerpt, category, author_name, published_at, read_time_minutes, featured_image_url"
    ).eq("is_published", true).order("published_at", { ascending: false }).limit(cap);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var get_blog_post_default = defineTool3({
  name: "get_blog_post",
  title: "Get a Setupr blog post",
  description: "Fetch the full content of a single published Setupr blog post by slug (markdown content, title, excerpt, author, category, published date, featured image).",
  inputSchema: {
    slug: z3.string().min(1).describe("The blog post slug, e.g. 'starting-a-business-in-india'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("blog_posts").select(
      "title, slug, excerpt, content, category, author_name, published_at, read_time_minutes, featured_image_url"
    ).eq("slug", slug).eq("is_published", true).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No published post found for slug '${slug}'.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "setupr-mcp",
  title: "Setupr",
  version: "0.1.0",
  instructions: "Public read-only tools for Setupr \u2014 the global digital services platform for business registration, websites & integrations, and automations & AI. Use `list_services` to browse the services catalog, `list_blog_posts` to browse published articles, and `get_blog_post` to read a full post by slug.",
  tools: [list_services_default, list_blog_posts_default, get_blog_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
